/*
 * BTG QC v19.5.32 – Rundtur, funktionsguide och Kom igång-checklista
 * Fristående modul. Kräver ingen SQL. Sparar användarval i localStorage.
 */
(function(){
  'use strict';
  const NS='btgOnboardingV19532';
  const LS={seen:NS+':seenWelcome', tourDone:NS+':tourDone', checklist:NS+':checklist'};
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const svList=arr=>arr.map(x=>`<li>${esc(x)}</li>`).join('');
  const now=()=>new Date().toISOString();
  const storageGet=(k,fb)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??fb}catch{return fb}};
  const storageSet=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
  const clickTab=name=>{const b=$(`.tab-btn[data-tab="${CSS.escape(name)}"]`); if(b) b.click(); else $(`[data-nav="${CSS.escape(name)}"]`)?.click();};

  const guideItems=[
    {id:'dashboard',title:'Dashboard',what:'Dashboarden visar en snabb överblick över fabrikens nuläge.',uses:['Se status','Hitta varningar','Följa cementnivåer','Se senaste provningar','Se avformningar','Komma åt viktiga funktioner snabbt'],steps:['Öppna Dashboard.','Kontrollera statuskorten.','Titta på eventuella varningar.','Följ upp cementnivåer, provningar och avformningar.','Klicka vidare till den funktion som behöver åtgärdas.']},
    {id:'material',title:'Material',what:'Materiallistan innehåller alla material som används i recept, klimatberäkningar och silokopplingar.',uses:['Lägga till cement','Lägga till ballast','Lägga till tillsatsmedel','Ange klimatdata/GWP','Koppla material till recept och silor'],steps:['Gå till Material.','Lägg till nytt material.','Ange namn, typ och relevanta värden.','Spara materialet.','Använd materialet i recept eller Cement & Silor.']},
    {id:'recept',title:'Recept',what:'Recept används för att skapa och hantera betongblandningar.',uses:['Bygga recept','Räkna materialmängder','Koppla hållfasthetsklass och exponeringsklass','Styra cementförbrukning','Skapa underlag för tillverkning och rapporter'],steps:['Gå till Recept/Tillverkningsdata.','Skapa nytt recept.','Välj material och mängder.','Ange hållfasthetsklass och övriga uppgifter.','Spara receptet.','Använd receptet i Tillverkningsjournalen.']},
    {id:'tillverkning',title:'Tillverkningsjournal',what:'Tillverkningsjournalen registrerar produktionen i fabriken.',uses:['Registrera satser','Välja recept','Ange volym/mängd','Koppla produktion till kund/order','Skapa underlag för provning och materialförbrukning'],steps:['Öppna Tillverkningsdata.','Välj recept.','Ange producerad mängd.','Kontrollera uppgifterna.','Spara satsen.','Följ upp provning och förbrukning.']},
    {id:'provningar',title:'Provkuber',what:'Provkuber används för att följa provtagningar och hållfasthetsresultat.',uses:['Skapa provkuber','Registrera resultat','Följa provålder','Se saknade resultat','Skapa kvalitetsunderlag'],steps:['Gå till Provningar.','Skapa eller öppna provning.','Kontrollera datum och recept.','Fyll i resultat när provningen är klar.','Följ upp avvikelser och saknade värden.']},
    {id:'avformning',title:'Avformningskuber',what:'Avformningskuber används för att kontrollera tidig hållfasthet inför avformning.',uses:['Följa tidiga hållfastheter','Se klara avformningar','Hitta saknade resultat','Identifiera låga värden','Skapa underlag för beslut'],steps:['Öppna Avformningskuber.','Kontrollera kuber som är klara för provning.','Fyll i resultat.','Följ upp låga eller saknade värden.','Använd resultatet i Kvalitetstrender.']},
    {id:'dagbok',title:'Dagbok',what:'Dagboken samlar viktiga händelser och anteckningar för fabriken.',uses:['Dokumentera leveranser','Registrera cementleveranser','Skriva driftanteckningar','Notera avvikelser','Följa upp händelser över tid'],steps:['Öppna Dagbok.','Skapa ny dagbokspost.','Välj typ av händelse.','Fyll i uppgifter.','Spara posten.','Om det är cementleverans, kontrollera att silon uppdateras.']},
    {id:'silos',title:'Cement & Silor',what:'Cement & Silor håller koll på cementlager i fabrikens silor.',uses:['Skapa silor','Koppla silo till cement','Ange kapacitet','Registrera leveranser','Se kg och procent','Följa cementförbrukning','Se trend över tid'],steps:['Öppna Cement & Silor.','Skapa en ny silo.','Välj cement från materiallistan.','Ange maxkapacitet och startsaldo.','Registrera inleveranser.','Använd recept i produktion.','Kontrollera att nivån räknas ner automatiskt.']},
    {id:'quality',title:'Kvalitetstrender',what:'Kvalitetstrender visar utveckling och bevakningspunkter för provning och avformning.',uses:['Se hållfasthetstrender','Jämföra provtagningar och avformningar','Hitta saknade resultat','Identifiera låga värden','Skapa rapporter'],steps:['Öppna Kvalitetstrender.','Välj period.','Kontrollera provtagningar.','Kontrollera avformningar.','Titta på bevakningspunkter.','Skapa rapport vid behov.']},
    {id:'rapporter',title:'Rapporter',what:'Rapporter skapar sammanställningar av produktion, provning, avformning och kvalitet.',uses:['Skapa vecko- och månadsrapporter','Dokumentera produktion','Följa upp kvalitet','Dela information via utskrift eller mail'],steps:['Öppna rapportfunktionen.','Välj rapporttyp.','Välj period.','Kontrollera sammanställningen.','Skriv ut eller skapa mailutkast.']},
    {id:'admin',title:'Fabriksadmin',what:'Fabriksadmin hanterar fabrikens användare, behörigheter och övergripande inställningar.',uses:['Hantera användare','Skapa accesskoder','Styra roller','Följa fabriksdata','Komma åt adminfunktioner'],steps:['Öppna Fabriksadmin.','Kontrollera användare och roller.','Skapa accesskod vid behov.','Tilldela rätt behörighet.','Följ upp att användaren ser rätt funktioner.']}
  ];

  const tourSteps=[
    {tab:'dashboard',selector:'#tab-dashboard',title:'Dashboard',text:'Dashboarden är startsidan där du snabbt får överblick över fabriken. Här ser du statuskort, senaste registreringar, cementnivåer, provningar, avformningar och varningar.',tip:'Börja alltid här om du vill se hur fabriken ligger till just nu.'},
    {selector:'.tab-btn[data-tab="material"]',title:'Material',text:'I Material lägger du in cement, ballast, tillsatsmedel, vatten och andra ingående material. Materialen används sedan i recept, beräkningar, cementlager och rapporter.',tip:'Lägg in cement och övriga huvudmaterial innan du skapar recept.'},
    {selector:'.tab-btn[data-tab="tillverkning"]',title:'Recept',text:'I Recept skapar du betongrecept med materialmängder, hållfasthetsklass, exponeringsklass och övriga egenskaper.',tip:'Kontrollera cementkopplingarna om du använder Cement & Silor.'},
    {tab:'tillverkning',selector:'#tab-tillverkning',title:'Tillverkningsjournal',text:'Tillverkningsjournalen används för att registrera satser och produktion. När du väljer recept och anger mängd kan systemet räkna materialförbrukning.',tip:'När en sats sparas kan cementförbrukningen räknas av från rätt silo.'},
    {selector:'.tab-btn[data-tab="provningar"]',title:'Provkuber',text:'Här hanterar du provkuber från provtagningar. Systemet håller reda på datum, recept, hållfasthetsklass, provålder, resultat och saknade värden.',tip:'Fyll i resultat löpande så blir rapporter och kvalitetstrender mer tillförlitliga.'},
    {selector:'.tab-btn[data-tab="dagbok"]',title:'Dagbok',text:'Dagboken används för viktiga händelser i fabriken, till exempel leveranser, driftstörningar, observationer, avvikelser och cementleveranser.',tip:'Cementleveranser ska registreras via rätt formulär så att silon uppdateras.'},
    {selector:'.tab-btn[data-tab="cement_silos"],#btnOpenCementSilos',title:'Cement & Silor',text:'Här skapar du silor, kopplar dem till cement från materiallistan och anger maxkapacitet samt startsaldo. Systemet visar aktuell nivå i kg och procent.',tip:'Skapa silorna tidigt så cementförbrukning kan följas från start.'},
    {selector:'.tab-btn[data-tab="quality_trends"],#btnOpenQualityTrends',title:'Kvalitetstrender',text:'Kvalitetstrender ger fabriksadmin överblick över provtagningar, avformningar, hållfasthetsutveckling, saknade resultat och bevakningspunkter.',tip:'Använd kvalitetstrender för att hitta mönster och åtgärdspunkter.'},
    {selector:'#btnNordcert,[id*="Report"],button',title:'Rapporter',text:'I rapportdelen skapar du sammanställningar för produktion, provning, avformning och kvalitet. Rapporter kan användas internt och för dokumentation.',tip:'Rapporter blir bäst när material, recept, satser och provresultat är ifyllda.'},
    {selector:'#btnSettings',title:'Fabriksadmin och inställningar',text:'Här hanteras inställningar, användare, behörigheter, accesskoder och funktioner som gäller hela fabriken.',tip:'Se över behörigheter när nya användare bjuds in.'}
  ];

  const checklistItems=[
    {id:'materials',title:'Skapa eller kontrollera material',desc:'Cement och övriga material behövs för recept och silor.',auto:()=>hasRows('#materialsTable tbody')||hasGlobal('MATERIALS')},
    {id:'recipes',title:'Skapa minst ett recept',desc:'Recept används i tillverkning, provning och cementförbrukning.',auto:()=>hasRows('#recipesTable tbody')||hasGlobal('RECIPES')},
    {id:'batches',title:'Registrera en sats',desc:'Satser ger produktionshistorik och materialförbrukning.',auto:()=>hasRows('#batchesTable tbody')||hasGlobal('BATCHES')},
    {id:'cubes',title:'Skapa eller kontrollera provkuber',desc:'Provkuber behövs för hållfasthet och kvalitetstrender.',auto:()=>hasRows('#cubesTable tbody')||hasGlobal('CUBES')},
    {id:'demoulding',title:'Registrera avformningskuber',desc:'Avformningsdata visar tidiga hållfastheter.',auto:()=>hasAnyText(['#demouldingCubesTable','#tab-demoulding','.demoulding-table'])},
    {id:'silo',title:'Skapa en silo i Cement & Silor',desc:'Silon visar cementlager i kg och procent.',auto:()=>hasAnyText(['#cementSilosGrid','.cement-silo-card'])},
    {id:'silo_cement',title:'Koppla silo till cement',desc:'Kopplingen gör att rätt cement räknas av.',auto:()=>hasAnyText(['#cementSilosGrid .sub','.cement-silo-card .sub'])},
    {id:'delivery',title:'Registrera en cementleverans',desc:'Leveranser ökar silons saldo.',auto:()=>hasAnyText(['#cementSilosMovements','.cement-dashboard-summary'])},
    {id:'dashboard_silos',title:'Kontrollera dashboardens cementnivåer',desc:'Se att 3D-silor och procent visas på dashboarden.',manual:true},
    {id:'quality',title:'Öppna Kvalitetstrender',desc:'Se trend och bevakningspunkter.',manual:true},
    {id:'report',title:'Skapa eller öppna en rapport',desc:'Kontrollera att rapportflödet fungerar.',manual:true},
    {id:'users',title:'Bjud in eller kontrollera användare',desc:'Säkerställ att rätt personer har rätt behörighet.',manual:true}
  ];
  function hasRows(sel){const tb=$(sel); return !!tb && $$('tr',tb).length>0 && (tb.textContent||'').trim().length>10;}
  function hasGlobal(name){try{return Array.isArray(window[name]) && window[name].length>0}catch{return false}}
  function hasAnyText(sels){return sels.some(s=>{const e=$(s); return !!e && (e.textContent||'').trim().length>8 && !/inga|saknas/i.test(e.textContent||'')})}

  let tour={i:0,active:false};
  function init(){ injectNav(); injectDashboardHelp(); injectChecklist(); injectGuideDialog(); injectTourShell(); injectWelcome(); bindGlobal(); updateChecklist(); }
  function injectNav(){ const nav=$('.main-nav'); if(!nav||$('#btnBtgHelpGuide')) return; const btn=document.createElement('button'); btn.className='btn secondary btg-help-nav-btn'; btn.id='btnBtgHelpGuide'; btn.type='button'; btn.textContent='? Hjälp / Guide'; const settings=$('#btnSettings'); nav.insertBefore(btn,settings||nav.lastChild); btn.addEventListener('click',openGuide); }
  function injectDashboardHelp(){ const hero=$('#productHeroCard')||$('#quickstartCard')||$('#tab-dashboard .card'); if(!hero||$('#btgOnboardingActions')) return; const box=document.createElement('div'); box.id='btgOnboardingActions'; box.className='btg-onboarding-actions'; box.innerHTML=`<button class="btn" id="btnStartBtgTour" type="button">Starta rundtur</button><button class="btn secondary" id="btnOpenBtgGuide" type="button">Funktionsguide</button>`; hero.appendChild(box); $('#btnStartBtgTour')?.addEventListener('click',()=>startTour(0)); $('#btnOpenBtgGuide')?.addEventListener('click',openGuide); }
  function injectChecklist(){ const dash=$('#tab-dashboard'); if(!dash||$('#btgChecklistCard')) return; const card=document.createElement('div'); card.className='card btg-checklist-card'; card.id='btgChecklistCard'; card.innerHTML=`<div class="btg-checklist-head"><div><h3>Kom igång</h3><p class="btg-checklist-sub">Följ stegen för att få fabriken redo. Vissa punkter bockas av automatiskt när systemet hittar data, andra kan du markera själv.</p></div><div class="btg-checklist-progress"><b id="btgChecklistCount">0/0 klara</b><div class="btg-checklist-bar"><div class="btg-checklist-fill" id="btgChecklistFill"></div></div></div></div><div class="btg-checklist-list" id="btgChecklistList"></div><div class="btg-checklist-tools"><button class="btn secondary" id="btnRefreshBtgChecklist" type="button">Uppdatera checklistan</button><button class="btn secondary" id="btnResetBtgChecklist" type="button">Nollställ manuella val</button><button class="btn" id="btnChecklistTour" type="button">Starta rundtur</button></div>`; const quick=$('#quickstartCard'); if(quick && quick.parentNode) quick.parentNode.insertBefore(card, quick.nextSibling); else dash.insertBefore(card, dash.firstChild); $('#btnRefreshBtgChecklist')?.addEventListener('click',updateChecklist); $('#btnResetBtgChecklist')?.addEventListener('click',()=>{storageSet(LS.checklist,{}); updateChecklist();}); $('#btnChecklistTour')?.addEventListener('click',()=>startTour(0)); }
  function updateChecklist(){ const list=$('#btgChecklistList'); if(!list) return; const saved=storageGet(LS.checklist,{}); const states={}; let done=0; checklistItems.forEach(item=>{ const auto = !item.manual && typeof item.auto==='function' && item.auto(); const checked = !!(auto || saved[item.id]); states[item.id]=checked; if(checked) done++; }); const total=checklistItems.length; list.innerHTML=checklistItems.map(item=>`<label class="btg-checklist-item ${states[item.id]?'done':''}"><input type="checkbox" data-btg-check="${esc(item.id)}" ${states[item.id]?'checked':''}><span><span class="btg-check-title">${esc(item.title)}</span><div class="btg-check-desc">${esc(item.desc)}${item.manual?'':' • Kan bockas av automatiskt.'}</div></span></label>`).join(''); $$('[data-btg-check]').forEach(ch=>ch.addEventListener('change',()=>{const s=storageGet(LS.checklist,{}); s[ch.dataset.btgCheck]=ch.checked; storageSet(LS.checklist,s); updateChecklist();})); $('#btgChecklistCount').textContent=`${done}/${total} klara`; $('#btgChecklistFill').style.width=`${Math.round(done/total*100)}%`; }
  function injectGuideDialog(){ if($('#btgGuideDialog')) return; const dlg=document.createElement('dialog'); dlg.id='btgGuideDialog'; dlg.className='btg-guide-dialog'; dlg.innerHTML=`<div class="btg-guide-shell"><aside class="btg-guide-side"><h3>Funktionsguide</h3><div class="btg-guide-tabs">${guideItems.map((g,i)=>`<button class="btg-guide-tab ${i===0?'active':''}" data-guide-id="${esc(g.id)}">${esc(g.title)}</button>`).join('')}</div></aside><main class="btg-guide-main"><div class="btg-guide-top"><div><h2 id="btgGuideTitle"></h2><p class="btg-checklist-sub" id="btgGuideWhat"></p></div><button class="btn secondary" id="btnCloseBtgGuide" type="button">Stäng</button></div><div id="btgGuideContent"></div></main></div>`; document.body.appendChild(dlg); $('#btnCloseBtgGuide')?.addEventListener('click',()=>dlg.close()); $$('.btg-guide-tab',dlg).forEach(b=>b.addEventListener('click',()=>renderGuide(b.dataset.guideId))); renderGuide(guideItems[0].id); }
  function renderGuide(id){ const g=guideItems.find(x=>x.id===id)||guideItems[0]; $$('.btg-guide-tab').forEach(b=>b.classList.toggle('active',b.dataset.guideId===g.id)); $('#btgGuideTitle').textContent=g.title; $('#btgGuideWhat').textContent=g.what; $('#btgGuideContent').innerHTML=`<div class="btg-guide-section"><h4>Används för att</h4><ul>${svList(g.uses)}</ul></div><div class="btg-guide-section"><h4>Steg för steg</h4><ol>${svList(g.steps)}</ol></div><div class="btg-guide-section"><button class="btn" type="button" data-guide-jump="${esc(g.id)}">Visa i appen</button></div>`; $('[data-guide-jump]')?.addEventListener('click',()=>{ $('#btgGuideDialog')?.close(); jumpToGuide(g.id); }); }
  function jumpToGuide(id){ const map={dashboard:'dashboard',material:'material',recept:'tillverkning',tillverkning:'tillverkning',provningar:'provningar',dagbok:'dagbok'}; if(map[id]) clickTab(map[id]); if(id==='silos') $('.tab-btn[data-tab="cement_silos"]')?.click(); if(id==='quality') $('.tab-btn[data-tab="quality_trends"]')?.click(); if(id==='dashboard_silos') clickTab('dashboard'); }
  function openGuide(){ const dlg=$('#btgGuideDialog'); if(dlg?.showModal) dlg.showModal(); else dlg?.setAttribute('open',''); }
  function injectTourShell(){ if($('#btgTourOverlay')) return; document.body.insertAdjacentHTML('beforeend',`<div class="btg-tour-overlay" id="btgTourOverlay"></div><div class="btg-tour-highlight" id="btgTourHighlight" style="display:none"></div><div class="btg-tour-pop" id="btgTourPop" style="display:none"><div class="btg-tour-meta" id="btgTourMeta"></div><h3 id="btgTourTitle"></h3><p id="btgTourText"></p><div class="btg-tour-tip" id="btgTourTip"></div><div class="btg-tour-actions"><div class="left"><button class="btn secondary" id="btnBtgTourSkip" type="button">Avsluta</button></div><div class="right"><button class="btn secondary" id="btnBtgTourPrev" type="button">Föregående</button><button class="btn" id="btnBtgTourNext" type="button">Nästa</button></div></div></div>`); $('#btnBtgTourSkip')?.addEventListener('click',endTour); $('#btnBtgTourPrev')?.addEventListener('click',()=>showTourStep(tour.i-1)); $('#btnBtgTourNext')?.addEventListener('click',()=> tour.i>=tourSteps.length-1 ? endTour(true) : showTourStep(tour.i+1)); window.addEventListener('resize',()=>tour.active&&showTourStep(tour.i,true)); }
  function startTour(i=0){ tour.active=true; $('#btgTourOverlay')?.classList.add('active'); showTourStep(i); }
  function endTour(done=false){ tour.active=false; $('#btgTourOverlay')?.classList.remove('active'); $('#btgTourHighlight').style.display='none'; $('#btgTourPop').style.display='none'; if(done) storageSet(LS.tourDone,{done:true,at:now()}); }
  function firstVisible(sel){ for(const part of String(sel).split(',')){ const el=$(part.trim()); if(el){ const r=el.getBoundingClientRect(); if(r.width||r.height) return el; } } return null; }
  function showTourStep(i,keep=false){ if(i<0) i=0; if(i>=tourSteps.length) i=tourSteps.length-1; tour.i=i; const s=tourSteps[i]; if(s.tab && !keep) clickTab(s.tab); setTimeout(()=>positionTour(s), keep?0:180); }
  function positionTour(s){ const target=firstVisible(s.selector)||$('#tab-dashboard')||document.body; target.scrollIntoView?.({behavior:'smooth',block:'center',inline:'center'}); setTimeout(()=>{ const rect=target.getBoundingClientRect(); const pad=8; const hi=$('#btgTourHighlight'); hi.style.display='block'; hi.style.left=Math.max(8,rect.left-pad)+'px'; hi.style.top=Math.max(8,rect.top-pad)+'px'; hi.style.width=Math.min(window.innerWidth-16,rect.width+pad*2)+'px'; hi.style.height=Math.min(window.innerHeight-16,rect.height+pad*2)+'px'; const pop=$('#btgTourPop'); $('#btgTourMeta').textContent=`Steg ${tour.i+1} av ${tourSteps.length}`; $('#btgTourTitle').textContent=s.title; $('#btgTourText').textContent=s.text; $('#btgTourTip').textContent=s.tip; $('#btnBtgTourPrev').disabled=tour.i===0; $('#btnBtgTourNext').textContent=tour.i===tourSteps.length-1?'Klart':'Nästa'; pop.style.display='block'; const rightSpace=window.innerWidth-rect.right; let left = rightSpace>450 ? rect.right+18 : rect.left; let top = rect.bottom+16; if(top+pop.offsetHeight>window.innerHeight-12) top=Math.max(12,rect.top-pop.offsetHeight-16); if(left+430>window.innerWidth-12) left=Math.max(12,window.innerWidth-442); pop.style.left=left+'px'; pop.style.top=top+'px'; },80); }
  function injectWelcome(){ if($('#btgWelcomeBox')||storageGet(LS.seen,false)) return; const box=document.createElement('div'); box.id='btgWelcomeBox'; box.className='btg-welcome-box'; box.innerHTML=`<h3>Välkommen till BTG Quality Control</h3><p>Vill du starta en snabb rundtur som visar material, recept, tillverkning, provningar, avformning, rapporter och fabriksadmin-funktioner?</p><div class="btg-onboarding-actions"><button class="btn" id="btnWelcomeStartTour" type="button">Starta rundtur</button><button class="btn secondary" id="btnWelcomeGuide" type="button">Funktionsguide</button><button class="btn secondary" id="btnWelcomeLater" type="button">Inte nu</button></div>`; document.body.appendChild(box); setTimeout(()=>box.classList.add('active'),900); $('#btnWelcomeStartTour')?.addEventListener('click',()=>{storageSet(LS.seen,true); box.remove(); startTour(0);}); $('#btnWelcomeGuide')?.addEventListener('click',()=>{storageSet(LS.seen,true); box.remove(); openGuide();}); $('#btnWelcomeLater')?.addEventListener('click',()=>{storageSet(LS.seen,true); box.remove();}); }
  function bindGlobal(){ document.addEventListener('click',e=>{ const t=e.target.closest('[data-nav],.tab-btn'); if(t) setTimeout(updateChecklist,600); }); document.addEventListener('btg:data-updated',()=>setTimeout(updateChecklist,300)); setInterval(updateChecklist,30000); window.BTG_ONBOARDING={startTour,openGuide,updateChecklist,resetWelcome:()=>localStorage.removeItem(LS.seen)}; }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',init); else init();
})();
